### ISSUE TITLE
Problem: AM services require manual start up in Vagrant environment 

### ISSUE THREAD

**Issue by hakamine** [artefactual/deploy-pub#22]
When restarting the vagrant VM (vagrant halt -> vagrant up), archivematica services (archivematica-dashboard, archivematica-mcp-server, archivematica-mcp-client) require manual start up:
$ sudo start archivematica-storage-service
$ sudo start archivematica-mcp-server
$ sudo start archivematica-mcp-client
$ sudo start archivematica-dashboard

Seeing the following errors in the upstart log files:

> Invalid value for chdir: /usr/lib/archivematica/storage-service
> Error: can't chdir to '/usr/lib/archivematica/storage-service'
> 
> Invalid value for chdir: /usr/share/archivematica/dashboard
> Error: can't chdir to '/usr/share/archivematica/dashboard'
> 
> /proc/self/fd/9: 4: /proc/self/fd/9: /usr/lib/archivematica/MCPServer/archivematicaMCP.py: not found
> 
> /proc/self/fd/9: 7: /proc/self/fd/9: /usr/lib/archivematica/MCPClient/archivematicaClient.py: not found

**Comment by sevein** [comment]
I think that we need something like: https://coderwall.com/p/1uwfhw/launch-upstart-services-after-vagrant-mount.

**Comment by sevein** [comment]
@hakamine check this out: https://serverfault.com/a/838390. That could be an easy fix. Maybe @sbreker wants to work on that. We could have the systemd unit template add that stuff when we're using Vagrant.

**Comment by hakamine** [comment]
I did a quick test on trusty (upstart), and it looks like adding a `vagrant-mounted` condition to the `start on` statement ( as described in http://razius.com/articles/launching-services-after-vagrant-mount/ ) in the archivematica upstart files (/etc/init/archivematica-dashboard.conf, etc) helps with the issue. I am dubious about where could be the best place to fix it, should we fix in the [ansible-archivematica-src](https://github.com/artefactual-labs/ansible-archivematica-src) role or in the playbook (adding a few tasks after the ansible-archivematica-src role is done)?

**Comment by sbreker** [comment]
Definitely interested in taking this on!

**Comment by sevein** [comment]
I think it's ok for the role to take care of that. The role already knows about distros or type of environments (prod, dev...) - this wouldn't be very different from that.

**Comment by hakamine** [comment]
@sbreker great! Would you like me to try to tackle first this in upstart and leave you to work on the systemd part, or would you prefer to work on both? (the fix for upstart I was thinking about is related with the comment above of using the `vagrant-mounted` event, so in theory it shouldn't be that hard)

**Comment by sbreker** [comment]
Hi @hakamine

I am going to look into this today.  If you can point me in the right
direction for the upstart stuff, I should be able to handle that too.

Steve

**Comment by hakamine** [comment]
@sbreker For the upstart thing, I was thinking about updating the upstart templates in https://github.com/artefactual-labs/ansible-archivematica-src (e.g., https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/templates/etc/upstart/archivematica-dashboard.conf.j2 ) so that the `start on` line also includes the `vagrant-mounted` event when deploying with vagrant, I think this can be checked with the `archivematica_src_environment_type` (when deploying with vagrant it is set to "development").

**Comment by sevein** [comment]
We haven't been able to replicate this issue in a while. Also, we're now using systemd.
