### ISSUE TITLE
Problem: acceptance-tests are not installed

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/deploy-pub#35]
Based on instructions at https://github.com/artefactual-labs/archivematica-acceptance-tests, create ansible tasks/roles that install the AM acceptance tests and their dependencies:

- acceptance tests and Python deps
- Xvfb
- firefox v. 47 (or a chrome version that gets the tests to pass reliably)

**Comment by sevein** [comment]
@scollazo, can we use chromimum 59 which brings headless support? https://developers.google.com/web/updates/2017/04/headless-chrome - would that be possible or easier?

**Comment by sevein** [comment]
This was fixed. Both stable/1.6.x and qa/1.7.x in the AM Ansible role install the acceptance tests and its dependencies when requested.
