### ISSUE TITLE
Xenial ubuntu user needs known password

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/deploy-pub#42]
Some acceptance tests need to be able to `scp` files from VM to local and therefore need to know the password for the ubuntu user created by the ubuntu/xenial64 box. However, this user has no password (that I can ascertain)—see https://bugs.launchpad.net/cloud-images/+bug/1569237. Solution would seem to be to specify the ubuntu user's password in the archivematica-xenial/Vagrantfile.

**Comment by sevein** [comment]
If you're using Vagrant, `vagrant ssh-config` is what you should be using. Just authenticate exactly as the output of that command describes. I've found an example here: https://stackoverflow.com/a/12938524. `scp -F` can read that format (not sure from STDIN). You could also use `paramiko.ssh.SSHConfig` but I don't know if paramiko comes with support for file transfer.

**Comment by jrwdunham** [comment]
Thanks sevein! Looks like I'll have to add another option (and some documentation) to the acceptance tests (in particular, `scp_server_file_to_local` of archivematicaselenium.py) so that `scp`-requiring tests can use the path to a specified identity file instead of a password. I'll close the issue here and open [a new one in the acceptance tests repo](https://github.com/artefactual-labs/archivematica-acceptance-tests/issues/20), assigned to me.

**Comment by sevein** [comment]
Cool. I would also try to consider scp just another file transport because it's likely that not all the environments are going to provide scp, e.g. in RDSS, scp is not going to be a thing at all. The files you're trying to access may be available as some kind of network share (perhaps nfs or some transparent mount point in the filesystem).
