### ISSUE TITLE
Problem: default archivematica deploy uses non-existent oracle java installer

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/deploy-pub#48]
This is an example: https://github.com/artefactual/deploy-pub/blob/master/playbooks/archivematica/vars-singlenode-qa.yml#L15-L16

As described in artefactual-labs/ansible-elasticsearch#5 and artefactual-labs/ansible-elasticsearch#3 the oracle java installer referenced in the lines above no longer exists.

These lines could be removed entirely from the vars-singlenode files, relying on the defaults defined in the ansible-elasticsearch role instead.

**Comment by scollazo** [comment]
Fixed in https://github.com/artefactual/deploy-pub/pull/49
