### ISSUE TITLE
Problem: Archivematica 1.7 playbook fails due to missing java dependency

### ISSUE THREAD

**Issue by joel-simpson** [artefactual/deploy-pub#71]
I installed Archivematica version 1.7.0 onto a digital ocean VM (using the [digital-ocean-install-example.rst](https://github.com/artefactual/deploy-pub/blob/master/playbooks/archivematica/docs/digital-ocean-install-example.rst))

Running the singlenode.yml playbook failed attempting to install dependencies for ElasticSearch: 

> TASK [artefactual.elasticsearch : Install dependencies] *******************************************************************************************************************
> fatal: [am-local]: FAILED! => {"changed": false, "msg": "No package matching 'openjdk-7-jre-headless' is available"}

I updated the playbook to replace '7' with '8' in the following 2 lines: 
`elasticsearch_apt_java_package: "openjdk-7-jre-headless"`
`elasticsearch_java_home: "/usr/lib/jvm/java-7-openjdk-amd64"`

I was then able to re-run the playbook and complete the installation successfully.

**Comment by jhsimpson** [comment]
@joel-simpson you were using the archivematica playbook, correct, as opposed to the archivematica-xenial playbook?  And you were deploying to ubuntu 16.04 I am guessing?

**Comment by joel-simpson** [comment]
Yes and yes... I was using archivematica playbook on Ubuntu 16.04
