### ISSUE TITLE
Problem: MySQL service down in AtoM Trusty playbook

### ISSUE THREAD

**Issue by jraddaoui** [artefactual/deploy-pub#74]
We have changed the Ubuntu version check to install the Percona server in https://github.com/artefactual-labs/ansible-percona/commit/16a44e5631883d2488afd065fc5a069e1e23bbc6

After those changes it installs Percona 5.6 by default in Ubuntu Trusty if it's not changed in the playbook using the new `mysql_version_major` and `mysql_version_minor` variables.

**Comment by hakamine** [comment]
@jraddaoui the ansible-percona travis test for trusty [passed](https://travis-ci.org/artefactual-labs/ansible-percona/jobs/375839326) with the default of 5.6 so this is unexpected 😞. Anything helpful in the error logs? 
According to [percona lifecycle doc](https://www.percona.com/services/policies/percona-software-platform-lifecycle) only subscribers get security updates/bug fixes for 5.5 (so having 5.6 working on trusty would be a good thing).

**Comment by jraddaoui** [comment]
Hi @hakamine ,

In atom-trusty, using Percona 5.6, when the "Purge database" task is reached, MySQL is down:

```
TASK [artefactual.atom : Purge database] ***************************************
fatal: [atom-local]: FAILED! => {"changed": true, "cmd": ["php", "symfony", "tools:purge", "--no-confirmation", "--email=demo@example.com", "--username=demo", "--password=demo", "--title=AtoM", "--description=Access to Memory", "--url=http://undefined"], "delta": "0:00:02.138478", "end": "2018-05-10 19:02:17.061185", "msg": "non-zero return code", "rc": 1, "start": "2018-05-10 19:02:14.922707", "stderr": "\n                                                                                                                      \n  Unable to open PDO connection [wrapped: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)]  \n                                                                                                                      ", "stderr_lines": ["", "                                                                                                                      ", "  Unable to open PDO connection [wrapped: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)]  ", "                                                                                                                      "], "stdout": "", "stdout_lines": []}
```

Here's `/var/log/mysql/error.log` after that fail, which looks to be a normal shutdown ...

https://gist.github.com/jraddaoui/89543b2d7901e5e72987628cc3cbaaed

**Comment by jraddaoui** [comment]
And `sudo service mysql start` does not bring it up and does not add anything to that log.

**Comment by hakamine** [comment]
@jraddaoui It looks like the problem is not with percona 5.6 but with the playbook running the role `ansible-percona-client` that installs a 5.5 client, just right after the `ansible-percona` role installs the 5.6 server. The `ansible-percona-client` is not required (the `ansible-percona` role with install both server and client). I created PR #78 with a fix.

**Comment by jraddaoui** [comment]
That's a lot better, thanks @hakamine!

**Comment by jraddaoui** [comment]
I've tested in both Vagrant boxes and merged.
