### ISSUE TITLE
Problem: some vars- files are missing MySQL users and databases 

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/deploy-pub#80]
Compare the following two files

- https://github.com/artefactual/deploy-pub/blob/master/playbooks/archivematica/vars-singlenode-1.7.yml
- https://github.com/artefactual/deploy-pub/blob/master/playbooks/archivematica/vars-singlenode-qa.yml

The first contains the following but the second does not:

    mysql_databases:
      - name: "{{ archivematica_src_am_db_name }}"
        collation: "utf8_general_ci"
        encoding: "utf8"

    mysql_users:
      - name: "{{ archivematica_src_am_db_user }}"
        pass: "{{ archivematica_src_am_db_password }}"
        priv: "{{ archivematica_src_am_db_name }}.*:ALL,GRANT"
        host: "{{ archivematica_src_am_db_host }}"

**Comment by sevein** [comment]
Fixed in https://github.com/artefactual/deploy-pub/pull/81.
